# Configure File for Snakemake

# Data and Intermediate File Storage
tmp_dir: "tmp"
data_dir: "data"
trees_dir: "1KGP_trees"
analysis_dir: "analysis"
results_dir: "results"
figure_dir: "figures"
path_to_relate: "relate_v1.2.4_x86_64_static"

# Paralelle
total_parallel: 12
